### ISSUE TITLE
It is impossible to multiply a Data object by a scalar with variance

### ISSUE THREAD

**Issue by jamesrhester** [Gumtree/gumtree#2]
Inspection of .../scripts/gumpy/nexus/data.py, method **mul**, suggests that it is impossible to multiply a 2D dataset by a scalar with variance.  If a true scalar is passed to this routine, ovar is set to 0.  If a one-element Data object is passed containing value and variance, the EltMultiply method is called which expects a match in dimensions.  

Please add to the **mul** and **imul** routines to include logic for detecting a single-element Data object and calling the EMath.toScale routine.

**Comment by nxi** [comment]
Resolved.
Create a new Dataset with a single value and variance will do it. 
d=Dataset([val], [var])
new_dataset = old_dataset * d
